### ISSUE TITLE
Not go gettable

### ISSUE THREAD

**Issue by niklas88** [ad-freiburg/gantry#3]
The `go get github.com/ad-freiburg/gantry` command doesn't work as is. For one the `main.go` isn't in the package root, then doing `go build cmd/gantry/main.go` in the `$GOPATH/src/github.com/ad-freiburg/gantry` doesn't work as being in the `$GOPATH` disables Go modules currently which leads to the cobra module not being found. Interestingly `go get github.com/ad-freiburg/gantry/cmd/gantry` seems to work so I think moving the command to the main package would fix this.

See also [here](https://github.com/golang/go/wiki/Modules#why-does-installing-a-tool-via-go-get-fail-with-error-cannot-find-main-module) though. So maybe we shouldn't advertise `go get` and instead just a clone + `go build`, though again having the `main.go` in the project root would make this much cleaner.

**Comment by lehmann-4178656ch** [comment]
A main in the root is good as long as a project only provides a single binary. Another flaw of the `go get` variant is that the version is not set as this relies on a preprocessor command. I'll remove the section from the readme for now.

**Comment by niklas88** [comment]
I think being able to `go get` would be really nice. Another problem with the current approach is that building from source results in a binary called `main` which means one has to rename it before putting it into the `$PATH` and also makes `go install` infeasible.  I think since the `gantry` executable is the main thing of this repository it really should be in the root folder and allow `go get`. You can always have additional executables that are in subfolders.

**Comment by lehmann-4178656ch** [comment]
gantry is already go gettable
```
% docker run --rm -it golang:1.12.6-alpine /bin/sh
Unable to find image 'golang:1.12.6-alpine' locally
1.12.6-alpine: Pulling from library/golang
921b31ab772b: Already exists 
2d3896533852: Pull complete 
28c34ce20860: Pull complete 
9186bf07c4ae: Pull complete 
7f1720e95b4b: Pull complete 
Digest: sha256:c750d6718009f2e94cb20f56a87884f601f175d43c9418ae0fa21ea00ad6a2ff
Status: Downloaded newer image for golang:1.12.6-alpine
/go # apk add git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/5) Installing nghttp2-libs (1.38.0-r0)
(2/5) Installing libcurl (7.65.1-r0)
(3/5) Installing expat (2.2.6-r0)
(4/5) Installing pcre2 (10.33-r0)
(5/5) Installing git (2.22.0-r0)
Executing busybox-1.30.1-r2.trigger
OK: 21 MiB in 20 packages
/go # go get github.com/ad-freiburg/gantry/cmd/gantry
/go # which gantry
/go/bin/gantry
/go # gantry
2019/06/25 08:12:58 No environment file is used
2019/06/25 08:12:58 pipeline Could not open pipeline definition.
...
```
But I'll rename the `main.go` to `gantry.go`
