### ISSUE TITLE
[Feature Request] Binary releases for non x86_64 architectures

### ISSUE THREAD

**Issue by niklas88** [ad-freiburg/gantry#50]
I already tested and used gantry on the following architectures: `x86_64/amd64`, `arm`, `s390x` and could also test on `arm64`. Yet, we only provide binaries for `x86_64`.  I think we should provide binary releases (via cross compile) for all the architectures we can test on.

**Comment by lehmann-4178656ch** [comment]
I've found [goreleaser](https://github.com/goreleaser/goreleaser) and am currently trying to set it up in my fork of gantry:

https://github.com/lehmann-4178656ch/gantry/tree/goreleaser

To test it please install goreleaser (I did not test this with the docker container but with an install from source)
```
goreleaser --snapshot
```
This then should generate
```
gantry_linux_arm64.tar.gz 
gantry_linux_armv7.tar.gz 
gantry_linux_armv6.tar.gz 
gantry_linux_s390x.tar.gz
gantry_linux_x86_64.tar.gz
```

If this works as needed it can be included to be run [automatically](https://goreleaser.com/ci/) when a new release is tagged.

**Comment by niklas88** [comment]
Will try this out. Also I think we should mention the supported architectures in the README.md

**Comment by niklas88** [comment]
Since we test on POWER now I think we should also add that. I currently don't have access to a native POWER box but could try on QEMU.

**Comment by lehmann-4178656ch** [comment]
I've just updated my branch to factor in the problems `goreleaser` has with handling `dist/.gitignore`. `i386` was never added by me.

**Comment by niklas88** [comment]
yeah I guess I saw it on the gorelease page

**Comment by lehmann-4178656ch** [comment]
I've tried adding a workflow action to automate this in the master of my fork:

https://github.com/lehmann-4178656ch/gantry/releases/tag/v0.5.1
https://github.com/lehmann-4178656ch/gantry/commit/4ffb2e2ffe52e7f0c8fe189f6a9ce1075cd2bf83/checks?check_suite_id=317932376

On problem is that the version number is not set, I think it has to be in the env as goreleaser does not execute commands I think.
