### ISSUE TITLE
gantry start <argument> unexpected behavior

### ISSUE THREAD

**Issue by hannahbast** [ad-freiburg/gantry#60]
I tried the following command, where <some_step> is one of the steps defined in `gantry.def.yml`:

```
gantry start <some_step>
```

The resulting behavior was unexpected: the whole pipeline was executed, as if I had only typed `gantry`.

There should either be an error message (because start <some_step> is not allowed) or the behavior should be such that that the specified step is executed.

Is there anything that speaks against the latter?

UPDATE: The same actually happens for any invalid command. For example, when I type `gantry xxx`

**Comment by lehmann-4178656ch** [comment]
Which gantry version is used? The behavior changed a bit in the past.

One thing against the proposed behavior (to only execute the specified step) is the compatibility with `docker-compose`. `docker-compose start x` starts `x` and all requirements (`depends_on`) of `x`. So I am forced to start all entries the pipeline up to `x`.

Version v0.5.0 should handle the selection of an existing service or step correctly:
```
$ cd gantry/examples/docker-compose
$ gantry --version
gantry version v0.5.0-0-g06c0e5c
$ gantry db
2019/12/09 23:08:34 pipeline - Starting: docker-compose_db
2019/12/09 23:08:34 docker-compose_db 23488e5cf20287b70608ac8b3c7be5ffdd0e31d486bff10b27bc5ee8d7459d3b
2019/12/09 23:08:35 pipeline - Starting: docker-compose_wordpress
2019/12/09 23:08:35 pipeline - Skipping: docker-compose_wordpress!
...
```

The error message part is currently missing and I've missed to implement that. I'm currently writing some tests to explicitly check the behavior of the docker-compose wordpress example and to catch if gantry is invoked on non existing services or steps.
```
gantry start foo
...
no such service or step: foo
```
